config/routes.rb
Rails.application.routes.draw do
  root 'sessions#signin'

  get 'ui(/:action)', controller: 'ui'

  #session routes
  get '/signin', to: 'sessions#signin', as: :signin
  post '/login', to: 'sessions#login', as: :login
  get '/logout', to: 'sessions#logout', as: :logout

  #resources routes
  resources :questions, only: [:new, :index, :create, :show] do
    member do
      post :vote
    end

    resources :answers, only: [:create] do
      member do
        post :vote
      end
    end
  end

  post '/users', to: 'users#create', as: :create_user
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  include Voteable

  belongs_to :question
  belongs_to :user
  validates_presence_of :description
  validates :description, length: {minimum: 10}
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :questions
end

app/models/question.rb
class Question < ActiveRecord::Base
  include Voteable

  belongs_to :user
  belongs_to :category
  has_many :answers , -> { order 'created_at desc' }
  validates_presence_of :title

  def most_relevant_answer
    max_score = 0
    most_relevant = nil

    answers.each do |answer|
      if answer.total_votes > max_score
        most_relevant = answer
      end
    end

    most_relevant
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :questions
  has_many :anwsers
  has_many :votes 
  has_secure_password validations: false
  validates_presence_of :email, :username, :password
  validates_uniqueness_of :email, :username 
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :voteable, polymorphic: true
  validates_uniqueness_of :user, scope: [:voteable_id, :voteable_type]
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :require_user
  before_action :set_question

  def create
    @answer = set_new_answer 

    if user_double_answers? 
      redirect_to question_path(@question)
      flash[:notice] = "You can not answer a question twice"
    elsif @answer.save 
      redirect_to question_path(params[:question_id])
    else
      render 'questions/show'
    end
  end 

  def vote
    @answer = Answer.find(params[:id])
    @vote = Vote.create(user: current_user, vote: params[:vote], voteable: @answer)
    redirect_to :back
  end

  private
  def answer_params
    params.require(:answer).permit(:description)
  end

  def set_question
   @question =  Question.find(params[:question_id])
  end

  def set_new_answer
    @question.answers.build(answer_params.merge!(user: current_user))
  end

  def user_double_answers?
    Answer.where("user_id = ? and question_id = ?", "#{current_user.id}", "#{set_question.id}").present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  
  helper_method :current_user
  
  def current_user
    User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      redirect_to signin_path
    end
  end

  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :require_user

  def index
    @questions = Question.all  
  end

  def new
    @question = Question.new
  end

  def show
    @question = set_question
  end
  
  def create
    @question = Question.create(question_params.merge!(user_id: current_user.id))
    if @question.save
      if params[:question][:category_id].present? 
        @question.category = Category.find(params[:question][:category_id])
        @question.save
      end
      flash[:notice] = 'Your question has been succesfully posted!'
      redirect_to question_path(@question)
    else
      render :new
    end
  end

  def vote
    @question = set_question
    @vote = Vote.create(user:current_user, voteable: @question, vote: params[:vote])
    redirect_to :back
  end

  private

  def set_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :description)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def signin
    if session[:user_id]
      redirect_to questions_path
    else
      @user = User.new
      render :signin
    end
  end

  def login 
    user = User.where(username: params[:username]).first
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = 'You have succesfully loged in '
      redirect_to questions_path
    else
      flash[:notice] = 'There is a problem on your username or password'
      redirect_to signin_path
    end
  end

  def logout
    session[:user_id] = nil
    flash[:notice] = 'You have successfully logged out'
    redirect_to signin_path
  end
end

app/controllers/ui_controller.rb
class UiController < ApplicationController
   
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    @user = User.create(user_params)
    if @user.save
      flash[:notice] = 'Your account was succesfully created'
      session[:user_id] = @user.id
      redirect_to questions_path
    else
      render 'sessions/signin'
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :username)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Qoverflow</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
  <%= csrf_meta_tags %>
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/questions/index.html.haml
.container
  = render partial: 'shared/navbar_ui'
  .row
    .col-xs-7.col-xs-offset-2 
      -@questions.each do |question|
        .row
          .col-xs-12
            - if question.category.present?
              %span.badge 
                = question.category.name
            = link_to question_path(question) do
              %h3.question-title
                = question.title
            = link_to vote_question_path(question, vote: true), method: 'post' do
              %button.btn.btn-default.upvote 
                Upvote | #{question.total_votes} 
            = link_to vote_question_path(question, vote: false), method: 'post' do
              %small.downvote Downvote
            %small.pull-right
              by 
              %strong #{question.user.username} 
              at #{question.created_at.strftime("%b %d, %Y")}
            %p.most-relevant-answer
              = simple_format(question.most_relevant_answer.description.truncate(400)) if question.most_relevant_answer
  = render partial: 'shared/footer'

app/views/questions/new.html.haml
.container
  =render partial: "shared/navbar_ui"
  .row
    .col-md-12
      %h1.text-center What's your question?

  = bootstrap_form_for(@question, layout: :horizontal, label_col: "col-sm-2 col-sm-offset-1", control_col: "col-sm-6") do |f|
    = f.text_field :title, placeholder: 'Enter question title'
    = f.text_area :description, placeholder: 'Enter description', rows: '9'
    = f.collection_select :category_id, Category.all, :id, :name,:include_blank => 'Select a Category'
    .form-group
      .col-sm-offset-3.col-sm-6
        = f.submit 'Post Question!', :class => 'btn btn-danger'
  =render 'shared/footer'

app/views/questions/show.html.haml
.container
  =render 'shared/navbar_ui'
  .row
    .col-xs-7.col-xs-offset-2 
      %h3.title
        = @question.title
      %p
        = @question.description
      = link_to vote_question_path(@question, vote: true), method: 'post' do
        %button.btn.btn-default.upvote 
          Upvote | #{@question.total_votes} 
      = link_to vote_question_path(@question, vote: false), method: 'post' do    
        %small.downvote Downvote
      %small.pull-right
        =@question.created_at.strftime("%b %d, %Y")
      %hr.question-separation
      %h4 
        = @question.answers.size
        Answers
      %hr
      .well
        %p.contributor-name 
          = current_user.username
        = form_for([@question, @question.answers.build]) do |f|  
          .form-group
            = f.text_area :description, class: 'form-control', placeholder: 'Write your answer', rows: '3' 
            %p.help-block Be constructive and do not insult other people :)
          = f.submit 'Write Answer', class: 'btn btn-default write-answer ' 

      - @question.answers.reload.each do |answer|
        %hr
        %p.contributor-name
          =answer.user.username
        %p
          = simple_format(answer.description)
        = link_to vote_question_answer_path(answer, question_id: @question.id, vote: true), method: 'post' do
          %button.btn.btn-default.upvote 
            Upvote | #{answer.total_votes}
        = link_to vote_question_answer_path(answer, question_id: @question.id, vote: false), method: 'post' do    
          %small.downvote Downvote
        %small.pull-right 
          by 
          %strong #{answer.user.username} 
          at #{answer.created_at.strftime("%b %d, %Y")}
  = render partial: 'shared/footer'

app/views/shared/_footer.html.haml
%footer
  %small
    Qoverflow @2015
    by
    %a{:href => "http://eduardo-blog.herokuapp.com/"} Eduardo Poleo
  %nav
    %ul
      %li
        %a{:href => "https://github.com/eduardopoleo"}
          %i.fa.fa-github
      %li
        %a{:href => "http://ca.linkedin.com/pub/eduardo-poleo/56/364/a4"}
          %i.fa.fa-linkedin-square

app/views/shared/_navbar_ui.html.haml
.col-xs-10.col-xs-offset-1
  %nav.navbar.navbar-default
    .container-fluid
      / Brand and toggle get grouped for better mobile display
      .navbar-header
        %button.navbar-toggle.collapsed{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand{:href => "#"} 
          %span#q> Q
          %span#o> overflow
      / Collect the nav links, forms, and other content for toggling
      #bs-example-navbar-collapse-1.collapse.navbar-collapse
        = link_to new_question_path, class: 'navbar-right', id: 'add-question' do
          %button.btn.btn-danger.navbar-btn{:type => "button"} 
            %i.fa.fa-pencil-square-o
            %span.add-question Add Question
        %ul.nav.navbar-nav.navbar-right
          %li
            = link_to 'All Questions', questions_path, id:'all-questions'
          %li.dropdown
            %a.dropdown-toggle{"aria-expanded" => "false", "data-toggle" => "dropdown", :href => "#", :role => "button"}
              = current_user.username 
              %span.caret
            %ul.dropdown-menu{:role => "menu"}
              %li
                = link_to 'Logout', logout_path 

app/views/ui/all_questions.html.haml
.container
  = render partial: 'shared/navbar_ui'

  %h2 Recent questions
  %hr
  .row
    .col-md-2 
      .well.col-md-0.text-center
        %i.fa.fa-arrow-up
        %br
        %span 4 votes
        %br
        %i.fa.fa-arrow-down
    .col-md-10 
      %h2 Some random questiion 1
      .user-details.text-center
        %p Aug 17'11 at 11:30
        %p by Hanna Bates 
  %hr
  .row
    .col-md-2 
      .well.col-md-0.text-center
        %i.fa.fa-arrow-up
        %br
        %span 4 votes
        %br
        %i.fa.fa-arrow-down
    .col-md-10 
      %h2 Some random questiion 1 what happens if the questions title gets really realllllly long lerolero lelr
      .user-details.text-center
        %p Aug 17'11 at 11:30
        %p by Hanna Bates  
  %hr
  .row
    .col-md-2 
      .well.col-md-0.text-center
        %i.fa.fa-arrow-up
        %br
        %span 4 votes
        %br
        %i.fa.fa-arrow-down
    .col-md-10 
      %h2 Some random questiion 1
      .user-details.text-center
        %p Aug 17'11 at 11:30
        %p by Hanna Bates
  = render partial: 'shared/footer'

app/views/ui/new_question.html.haml
.container
  =render partial: "shared/navbar_ui"
  .row
    .col-md-12
      %h1.text-center What's your question?

  %form.form-horizontal.form-margin
    .form-group
      %label.col-sm-2.col-sm-offset-1.control-label{:for => "title"} Title
      .col-sm-6
        %input#title.form-control{:placeholder => "Enter question title", :type => "text"}/ 
    .form-group
      %label.col-sm-2.col-sm-offset-1.control-label{:for => "description"} Description
      .col-sm-6
        %textarea#description.form-control{:placeholder => "Enter Description", :rows => "9"}
    .form-group
      %label.col-sm-2.col-sm-offset-1.control-label{:for => "category"} Category 
      .col-sm-6
        %select#category.form-control
          %option Suspense 
          %option Rcok
          %option yuca 
          %option papa
    .form-group
      .col-sm-offset-3.col-sm-6
        %button.btn.btn-info{:type => "submit"} Post!
  =render 'shared/footer' 

app/views/ui/show_question.html.haml
.container
  =render 'shared/navbar_ui'
  .row
    .col-xs-7.col-xs-offset-2 
      %h3 I could not solve an easy problem. Should I quit programming?
      %p I was trying to solve this: Find a substring within a string. If found, display its starting position.  I started learning C++ (first language) 6 months back and I have just completed functions, arrays and strings. This is probably the 10th problem that I am solving in strings and I could not do it although I am usually counted amongst the good students in my class at school. I made a program, it worked for some cases, then I discovered the newer cases and modified the existing program. This continued for around half an hour when I got frustrated and looked up the solution on the internet. After looking at the solution, I felt very stupid as it seemed to be so easy. I'm 17 and have had great interest in computers and gadgets and how they function; for a long time, so I want to work in good places and make something big. Will I ever be able to achieve that? I don't think this incident has anything to do with computers or programming. Is  it that my intelligence and thinking level are not good enough for  programming and coding? Should I quit and find something else?
      %button.btn.btn-default.upvote 
        Upvote | 21

      %small.downvote Downvote
      %small.pull-right 15 Feb, 2010
      %hr.question-separation
      %p 5 Anwsers
      %hr
      .well
        %p.contributor-name Jose de la vava
        %form
          .form-group
            %textarea#comment.form-control{:placeholder => "Write your anwser",:rows => "3"}
            %p.help-block Be constructive and do not insult other people :)
          %button.btn.btn-default.upvote{:type => "submit"} Write anwser 
      %hr
      %p.contributor-name Eduardo Poleo
      %p You are 17 and you are already learning arguably the hardest language to learn?! When I was 17 I was busy playing games with my friends and chasing girls ;)
      %p Don't whrry too much! My guess is that your failure was not exactly because you are not clever, but just because of lack of experience. Just keep practising and learn from your mistakes. Unless you want to work at NASA, most of 'real-life' programming problems are all the same as the old ones. Once you know one, you will remember the next time you encounter it.  Remember 'Practice makes Perfect'
      %button.btn.btn-default.upvote 
        Upvote | 21

      %small.downvote Downvote
      %small.pull-right 15 Feb, 2016
  = render partial: 'shared/footer'

app/views/ui/sing_in_ui.html.haml
#session
  .row
    .col-lg-2 
      %h1 Logo
    .col-lg-7 
      %h2 Sign up to start reading
      %lgall A world of questions... The source of knowledge
  .row
    .col-lg-6 
      .sign-up
        %h3 Sign Up 
        %form.form-horizontal
          .form-group
            %label.col-lg-4.control-label{:for => "inputEmail3"} Email
            .col-lg-8
              %input#inputEmail3.form-control{:type => "email"}/
          .form-group
            %label.col-lg-4.control-label{:for => "password"} Full Name
            .col-lg-8
              %input#password.form-control{:type => "password"}/
          .form-group
            %label.col-lg-4.control-label{:for => "re_password"} Password
            .col-lg-8
              %input#re_password.form-control{:type => "password"}/
          %p.help-block By clicking Sing Up your are entering in a weird world full of spiders and crazy ol ladies.
          .form-group
            .col-lg-offset-4.col-lg-8
              %button.btn.btn-default.pull-right{:type => "submit"} Sign in   
    .col-lg-5 
      .login
        %h3 Log In
        %form
          .form-group
            %input#attribute.form-control{:placeholder => "Enter email", :type => "email"}/
          .form-group
            %input#password.form-control{:placeholder => "Enter Password", :type => "password"}/
          %button.btn.btn-default.pull-right{:type => "submit"} Submit 
  .footprint
    %small
      @2015
      by
      %a{:href => "http://eduardo-blog.herokuapp.com/"} Eduardo Poleo
      for parody and training purposes
    %nav
      %ul
        %li
          %a{:href => "https://github.com/eduardopoleo"}
            %i.fa.fa-github
        %li
          %a{:href => "http://ca.linkedin.com/pub/eduardo-poleo/56/364/a4"}
            %i.fa.fa-linkedin-square